consul:
  command: agent -server -bootstrap -client=0.0.0.0
  image: consul:latest
  ports:
    - "8500:8500"
wol:
  build: ./services/wol
  links:
    - consul
dregistry:
  build: ./services/dregistry
  links:
    - consul
