// Code generated by protoc-gen-go.
// source: services/dregistry/proto/device.proto
// DO NOT EDIT!

/*
Package device is a generated protocol buffer package.

It is generated from these files:
	services/dregistry/proto/device.proto

It has these top-level messages:
	DeviceRegistry
	GetDeviceRequest
	GetDeviceResponse
	ViewRequest
	Device
*/
package device

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceRegistry struct {
	Devices map[string]*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *DeviceRegistry) Reset()                    { *m = DeviceRegistry{} }
func (m *DeviceRegistry) String() string            { return proto.CompactTextString(m) }
func (*DeviceRegistry) ProtoMessage()               {}
func (*DeviceRegistry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceRegistry) GetDevices() map[string]*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type GetDeviceRequest struct {
	Alias string `protobuf:"bytes,1,opt,name=Alias,json=alias" json:"Alias,omitempty"`
}

func (m *GetDeviceRequest) Reset()                    { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()               {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetDeviceRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type GetDeviceResponse struct {
	Device *Device `protobuf:"bytes,1,opt,name=Device,json=device" json:"Device,omitempty"`
}

func (m *GetDeviceResponse) Reset()                    { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()               {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetDeviceResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type ViewRequest struct {
	Service string   `protobuf:"bytes,1,opt,name=Service,json=service" json:"Service,omitempty"`
	Filter  []string `protobuf:"bytes,2,rep,name=Filter,json=filter" json:"Filter,omitempty"`
}

func (m *ViewRequest) Reset()                    { *m = ViewRequest{} }
func (m *ViewRequest) String() string            { return proto.CompactTextString(m) }
func (*ViewRequest) ProtoMessage()               {}
func (*ViewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ViewRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ViewRequest) GetFilter() []string {
	if m != nil {
		return m.Filter
	}
	return nil
}

type Device struct {
	Alias         string   `protobuf:"bytes,1,opt,name=Alias,json=alias" json:"Alias,omitempty"`
	Manufacturer  string   `protobuf:"bytes,2,opt,name=Manufacturer,json=manufacturer" json:"Manufacturer,omitempty"`
	Model         string   `protobuf:"bytes,3,opt,name=Model,json=model" json:"Model,omitempty"`
	SerialNumber  string   `protobuf:"bytes,4,opt,name=SerialNumber,json=serialNumber" json:"SerialNumber,omitempty"`
	HWAddress     string   `protobuf:"bytes,5,opt,name=HWAddress,json=hWAddress" json:"HWAddress,omitempty"`
	WakeUpMethod  string   `protobuf:"bytes,6,opt,name=WakeUpMethod,json=wakeUpMethod" json:"WakeUpMethod,omitempty"`
	HK_Accessory  string   `protobuf:"bytes,7,opt,name=HK_Accessory,json=hKAccessory" json:"HK_Accessory,omitempty"`
	BoundServices []string `protobuf:"bytes,8,rep,name=BoundServices,json=boundServices" json:"BoundServices,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Device) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Device) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Device) GetHWAddress() string {
	if m != nil {
		return m.HWAddress
	}
	return ""
}

func (m *Device) GetWakeUpMethod() string {
	if m != nil {
		return m.WakeUpMethod
	}
	return ""
}

func (m *Device) GetHK_Accessory() string {
	if m != nil {
		return m.HK_Accessory
	}
	return ""
}

func (m *Device) GetBoundServices() []string {
	if m != nil {
		return m.BoundServices
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceRegistry)(nil), "DeviceRegistry")
	proto.RegisterType((*GetDeviceRequest)(nil), "GetDeviceRequest")
	proto.RegisterType((*GetDeviceResponse)(nil), "GetDeviceResponse")
	proto.RegisterType((*ViewRequest)(nil), "ViewRequest")
	proto.RegisterType((*Device)(nil), "Device")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for DRegistry service

type DRegistryClient interface {
	View(ctx context.Context, in *ViewRequest, opts ...client.CallOption) (*DeviceRegistry, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...client.CallOption) (*GetDeviceResponse, error)
}

type dRegistryClient struct {
	c           client.Client
	serviceName string
}

func NewDRegistryClient(serviceName string, c client.Client) DRegistryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "dregistry"
	}
	return &dRegistryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dRegistryClient) View(ctx context.Context, in *ViewRequest, opts ...client.CallOption) (*DeviceRegistry, error) {
	req := c.c.NewRequest(c.serviceName, "DRegistry.View", in)
	out := new(DeviceRegistry)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRegistryClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...client.CallOption) (*GetDeviceResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DRegistry.GetDevice", in)
	out := new(GetDeviceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DRegistry service

type DRegistryHandler interface {
	View(context.Context, *ViewRequest, *DeviceRegistry) error
	GetDevice(context.Context, *GetDeviceRequest, *GetDeviceResponse) error
}

func RegisterDRegistryHandler(s server.Server, hdlr DRegistryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DRegistry{hdlr}, opts...))
}

type DRegistry struct {
	DRegistryHandler
}

func (h *DRegistry) View(ctx context.Context, in *ViewRequest, out *DeviceRegistry) error {
	return h.DRegistryHandler.View(ctx, in, out)
}

func (h *DRegistry) GetDevice(ctx context.Context, in *GetDeviceRequest, out *GetDeviceResponse) error {
	return h.DRegistryHandler.GetDevice(ctx, in, out)
}

func init() { proto.RegisterFile("services/dregistry/proto/device.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0xeb, 0xa4, 0xb1, 0xf1, 0xd8, 0x85, 0x76, 0x85, 0xd0, 0x2a, 0x2a, 0xc2, 0xac, 0x40,
	0xf8, 0xe4, 0x48, 0xa1, 0x42, 0x88, 0x0b, 0x0a, 0x14, 0xa8, 0x54, 0x85, 0x83, 0x2b, 0xe8, 0x11,
	0x39, 0xf6, 0x94, 0x98, 0x3a, 0x76, 0xd8, 0x5d, 0xb7, 0xf2, 0x2f, 0xe0, 0xc4, 0x7f, 0x46, 0xbb,
	0x6b, 0x47, 0x4b, 0xe1, 0xe6, 0xf9, 0xfc, 0xe6, 0xcd, 0xea, 0xcd, 0xc0, 0x73, 0x81, 0xfc, 0xa6,
	0xcc, 0x51, 0xcc, 0x0a, 0x8e, 0xdf, 0x4b, 0x21, 0x79, 0x37, 0xdb, 0xf2, 0x46, 0x36, 0xb3, 0x02,
	0x15, 0x4f, 0x74, 0xc1, 0x7e, 0x3b, 0x70, 0xff, 0x54, 0x83, 0xb4, 0x57, 0x91, 0x57, 0xe0, 0x19,
	0x89, 0xa0, 0x4e, 0x34, 0x8e, 0x83, 0xf9, 0x71, 0xf2, 0xb7, 0xa2, 0x2f, 0xc5, 0x87, 0x5a, 0xf2,
	0x2e, 0x1d, 0xc4, 0xd3, 0xf7, 0x10, 0xda, 0x3f, 0xc8, 0x21, 0x8c, 0xaf, 0xb1, 0xa3, 0x4e, 0xe4,
	0xc4, 0x7e, 0xaa, 0x3e, 0xc9, 0x63, 0x98, 0xdc, 0x64, 0x55, 0x8b, 0x74, 0x14, 0x39, 0x71, 0x30,
	0xf7, 0x06, 0x5f, 0x43, 0xdf, 0x8c, 0x5e, 0x3b, 0x2c, 0x86, 0xc3, 0x4f, 0x28, 0x87, 0x79, 0x3f,
	0x5b, 0x14, 0x92, 0x3c, 0x84, 0xc9, 0xa2, 0x2a, 0x33, 0xd1, 0x5b, 0x4d, 0x32, 0x55, 0xb0, 0x13,
	0x38, 0xb2, 0x94, 0x62, 0xdb, 0xd4, 0x02, 0xc9, 0x13, 0x70, 0x0d, 0xd1, 0x5a, 0x6b, 0x84, 0x6b,
	0x5e, 0xc9, 0xde, 0x42, 0xf0, 0xb5, 0xc4, 0xdb, 0xc1, 0x9a, 0x82, 0x77, 0x61, 0x72, 0xea, 0xcd,
	0xbd, 0x3e, 0x36, 0xf2, 0x08, 0xdc, 0x8f, 0x65, 0x25, 0x91, 0xd3, 0x51, 0x34, 0x8e, 0xfd, 0xd4,
	0xbd, 0xd2, 0x15, 0xfb, 0x35, 0x1a, 0x46, 0xfc, 0xff, 0x5d, 0x84, 0x41, 0xb8, 0xcc, 0xea, 0xf6,
	0x2a, 0xcb, 0x65, 0xcb, 0x75, 0xbb, 0xfa, 0x19, 0x6e, 0x2c, 0xa6, 0x3a, 0x97, 0x4d, 0x81, 0x15,
	0x1d, 0x9b, 0xce, 0x8d, 0x2a, 0x54, 0xe7, 0x05, 0xf2, 0x32, 0xab, 0x3e, 0xb7, 0x9b, 0x15, 0x72,
	0xba, 0x6f, 0x3a, 0x85, 0xc5, 0xc8, 0x31, 0xf8, 0x67, 0x97, 0x8b, 0xa2, 0xe0, 0x28, 0x04, 0x9d,
	0x68, 0x81, 0xbf, 0x1e, 0x80, 0x72, 0xb8, 0xcc, 0xae, 0xf1, 0xcb, 0x76, 0x89, 0x72, 0xdd, 0x14,
	0xd4, 0x35, 0x0e, 0xb7, 0x16, 0x23, 0x4f, 0x21, 0x3c, 0x3b, 0xff, 0xb6, 0xc8, 0x73, 0x14, 0xa2,
	0xe1, 0x1d, 0xf5, 0xb4, 0x26, 0x58, 0x9f, 0xef, 0x10, 0x79, 0x06, 0x07, 0xef, 0x9a, 0xb6, 0x2e,
	0xfa, 0x68, 0x04, 0xbd, 0xa7, 0x23, 0x38, 0x58, 0xd9, 0x70, 0xfe, 0x03, 0xfc, 0xd3, 0xdd, 0xd1,
	0xbc, 0x80, 0x7d, 0x95, 0x2b, 0x09, 0x13, 0x2b, 0xde, 0xe9, 0x83, 0x3b, 0x97, 0xc3, 0xf6, 0xc8,
	0x09, 0xf8, 0xbb, 0xb5, 0x91, 0xa3, 0xe4, 0xee, 0xb2, 0xa7, 0x24, 0xf9, 0x67, 0xab, 0x6c, 0x6f,
	0xe5, 0xea, 0x6b, 0x7d, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x94, 0x66, 0x7f, 0xab, 0xd6, 0x02,
	0x00, 0x00,
}
