// Code generated by protoc-gen-go.
// source: device.proto
// DO NOT EDIT!

/*
Package device is a generated protocol buffer package.

It is generated from these files:
	device.proto

It has these top-level messages:
	DeviceRegistry
	ViewRequest
	Device
*/
package device

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceRegistry struct {
	Devices []*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
}

func (m *DeviceRegistry) Reset()                    { *m = DeviceRegistry{} }
func (m *DeviceRegistry) String() string            { return proto.CompactTextString(m) }
func (*DeviceRegistry) ProtoMessage()               {}
func (*DeviceRegistry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceRegistry) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type ViewRequest struct {
	Alias string `protobuf:"bytes,1,opt,name=Alias,json=alias" json:"Alias,omitempty"`
}

func (m *ViewRequest) Reset()                    { *m = ViewRequest{} }
func (m *ViewRequest) String() string            { return proto.CompactTextString(m) }
func (*ViewRequest) ProtoMessage()               {}
func (*ViewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ViewRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type Device struct {
	Alias         string   `protobuf:"bytes,1,opt,name=Alias,json=alias" json:"Alias,omitempty"`
	HWAddress     string   `protobuf:"bytes,2,opt,name=HWAddress,json=hWAddress" json:"HWAddress,omitempty"`
	WakeUpMethod  string   `protobuf:"bytes,3,opt,name=WakeUpMethod,json=wakeUpMethod" json:"WakeUpMethod,omitempty"`
	BoundServices []string `protobuf:"bytes,4,rep,name=BoundServices,json=boundServices" json:"BoundServices,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Device) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Device) GetHWAddress() string {
	if m != nil {
		return m.HWAddress
	}
	return ""
}

func (m *Device) GetWakeUpMethod() string {
	if m != nil {
		return m.WakeUpMethod
	}
	return ""
}

func (m *Device) GetBoundServices() []string {
	if m != nil {
		return m.BoundServices
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceRegistry)(nil), "DeviceRegistry")
	proto.RegisterType((*ViewRequest)(nil), "ViewRequest")
	proto.RegisterType((*Device)(nil), "Device")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for DRegistry service

type DRegistryClient interface {
	View(ctx context.Context, in *ViewRequest, opts ...client.CallOption) (*DeviceRegistry, error)
}

type dRegistryClient struct {
	c           client.Client
	serviceName string
}

func NewDRegistryClient(serviceName string, c client.Client) DRegistryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "dregistry"
	}
	return &dRegistryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dRegistryClient) View(ctx context.Context, in *ViewRequest, opts ...client.CallOption) (*DeviceRegistry, error) {
	req := c.c.NewRequest(c.serviceName, "DRegistry.View", in)
	out := new(DeviceRegistry)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DRegistry service

type DRegistryHandler interface {
	View(context.Context, *ViewRequest, *DeviceRegistry) error
}

func RegisterDRegistryHandler(s server.Server, hdlr DRegistryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DRegistry{hdlr}, opts...))
}

type DRegistry struct {
	DRegistryHandler
}

func (h *DRegistry) View(ctx context.Context, in *ViewRequest, out *DeviceRegistry) error {
	return h.DRegistryHandler.View(ctx, in, out)
}

func init() { proto.RegisterFile("device.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe6, 0xe2, 0x73, 0x01, 0xf3, 0x83,
	0x52, 0xd3, 0x33, 0x8b, 0x4b, 0x8a, 0x2a, 0x85, 0x14, 0xb9, 0xd8, 0x21, 0x2a, 0x8a, 0x25, 0x18,
	0x15, 0x98, 0x35, 0xb8, 0x8d, 0xd8, 0xf5, 0xa0, 0x2a, 0x60, 0xe2, 0x4a, 0xca, 0x5c, 0xdc, 0x61,
	0x99, 0xa9, 0xe5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x8e, 0x39,
	0x99, 0x89, 0x20, 0xf5, 0x8c, 0x1a, 0x9c, 0x41, 0xac, 0x89, 0x20, 0x8e, 0x52, 0x1b, 0x23, 0x17,
	0x1b, 0x44, 0x23, 0x76, 0x05, 0x42, 0x32, 0x5c, 0x9c, 0x1e, 0xe1, 0x8e, 0x29, 0x29, 0x45, 0xa9,
	0xc5, 0xc5, 0x12, 0x4c, 0x60, 0x19, 0xce, 0x0c, 0x98, 0x80, 0x90, 0x12, 0x17, 0x4f, 0x78, 0x62,
	0x76, 0x6a, 0x68, 0x81, 0x6f, 0x6a, 0x49, 0x46, 0x7e, 0x8a, 0x04, 0x33, 0x58, 0x01, 0x4f, 0x39,
	0x92, 0x98, 0x90, 0x0a, 0x17, 0xaf, 0x53, 0x7e, 0x69, 0x5e, 0x4a, 0x70, 0x6a, 0x11, 0xc4, 0xc1,
	0x2c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0xbc, 0x49, 0xc8, 0x82, 0x46, 0x26, 0x5c, 0x9c, 0x2e, 0x70,
	0xdf, 0xa9, 0x73, 0xb1, 0x80, 0x9c, 0x2e, 0xc4, 0xa3, 0x87, 0xe4, 0x03, 0x29, 0x7e, 0x3d, 0xd4,
	0x40, 0x50, 0x62, 0x48, 0x62, 0x03, 0x87, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x81,
	0xd9, 0x63, 0x2f, 0x01, 0x00, 0x00,
}
